5.1.
Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B.


In [1]:
import numpy as np

In [10]:
a = np.array([[1, 2, 3, 4, 5]])

In [7]:
b = np.array([[1], [2], [3], [4], [5]])

In [11]:
a

array([[1, 2, 3, 4, 5]])

In [12]:
b

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [13]:
a.shape

(1, 5)

In [9]:
b.shape

(5, 1)

In [14]:
c = a * 2
c

array([[ 2,  4,  6,  8, 10]])

In [15]:
d = b * 2
d

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10]])

In [16]:
e = a + 1
e

array([[2, 3, 4, 5, 6]])

In [17]:
f = c + e
f

array([[ 4,  7, 10, 13, 16]])

In [18]:
g = a - e
g

array([[-1, -1, -1, -1, -1]])

In [21]:
print(e)
h = e.transpose()
print(" ")
print(h)

[[2 3 4 5 6]]
 
[[2]
 [3]
 [4]
 [5]
 [6]]


In [24]:
i = np.dot(e, h)
i

array([[90]])

In [25]:
j = np.dot(h, e)
j

array([[ 4,  6,  8, 10, 12],
       [ 6,  9, 12, 15, 18],
       [ 8, 12, 16, 20, 24],
       [10, 15, 20, 25, 30],
       [12, 18, 24, 30, 36]])

In [26]:
k = np.identity(5)
print(k)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [27]:
l = np.dot(j, k)
l

array([[ 4.,  6.,  8., 10., 12.],
       [ 6.,  9., 12., 15., 18.],
       [ 8., 12., 16., 20., 24.],
       [10., 15., 20., 25., 30.],
       [12., 18., 24., 30., 36.]])

In [28]:
m = np.dot(k, j)
m

array([[ 4.,  6.,  8., 10., 12.],
       [ 6.,  9., 12., 15., 18.],
       [ 8., 12., 16., 20., 24.],
       [10., 15., 20., 25., 30.],
       [12., 18., 24., 30., 36.]])